#!/bin/bash -x
# Purpose: generate Debian source package based on project's git repository
# schema:
# $debian_dir: and one directory for every distribution
# $debian_auto_version: how the automatic version is created
# $tagbase: tag to use for git describe
cd source

# debug info
env

# defaults
build_tag=false
TAG=unknown
BASE_DIR=${debian_dir:-"pkg"}
#BASE_DIR=${debian_dir:-"."}

if [ -n "$GIT_BRANCH" ] ; then
  case "$GIT_BRANCH" in
    origin/tags/*)
      build_tag=true
      TAG=${GIT_BRANCH#origin/tags/}
      ;;
  esac
else
#it's not external git
  build_tag=true
fi

if [ ! -d "$BASE_DIR" -a ! -d debian ]; then
  echo 'No $BASE_DIR nor debian/ found on source'
  exit 1
fi

if [ ! -d "$BASE_DIR" ]; then
  BASE_DIR="debian"
fi

git clean -fxd

if [ "$BASE_DIR"X != debianX ]; then
  mkdir -p debian
  cp -aL "${BASE_DIR}"/"${distribution}"/* debian/
  rm -rf "$BASE_DIR"
fi

case "$distribution" in
  squeeze)
    debstr=deb6
    ;;
  wheezy)
    debstr=deb7
    ;;
  raspwheezy)
    debstr=raspdeb7
    ;;
  jessie|testing)
    debstr=deb8
    ;;
  raspjessie)
    debstr=raspdeb8
    ;;
  sid|unstable)
    debstr=deb9
    ;;
  experimental)
    debstr=exp
    ;;
  lucid)
    debstr=ubuntu10.04
    ;;
  precise)
    debstr=ubuntu12.04
    ;;
  trusty)
    debstr=ubuntu14.04
    ;;
  utopic)
    debstr=ubuntu14.10
    ;;
  vivid)
    debstr=ubuntu15.04
    ;;
  *)
    debstr=$distribution
    ;;
esac

#automatically take care of non-multiarch packages
if [ $distribution = squeeze -o $distribution = lucid ]; then
  sed -i 's#usr/lib/\*#usr/lib#g' debian/*.install debian/rules
fi

export DEBEMAIL="CFEngine Debian Team <debain-team@cfengine.com>"

ORIG_VERSION=$(dpkg-parsechangelog --count 1 | awk '/^Version/ {print $2}')
TIMESTAMP="$(date -u +%Y%m%d%H%M%S)"
DISTRIBUTION=$(dpkg-parsechangelog --count 1 | awk '/^Distribution/ {print $2}')
AUTO_VERSION="${ORIG_VERSION}+0~${TIMESTAMP}.${BUILD_NUMBER}"

if [ -n "$debian_auto_version" ]; then
  case "$debian_auto_version" in
    sems)
      DESCRIBE=$(git describe --match "${tagbase}" --always)
      echo "*** setting sems auto_version from ${DESCRIBE} ***"
      DESCRIBE=$(echo -n ${DESCRIBE}| sed 's/^.*-\([0-9]\+\)-\([a-zA-Z0-9]\+\)$/\1~\2/')
      AUTO_VERSION="${ORIG_VERSION}+0~${DESCRIBE}"
      ;;
    esac
fi

if "$build_tag" ; then
  echo "*** Building a tagged version (${TAG}).***"
  dch -b --distribution="${DISTRIBUTION}" \
    --newversion="${ORIG_VERSION}~${debstr}" \
    -- "Automated package build for tag $TAG and distribution $distribution."
else
  echo "*** Building version (${AUTO_VERSION}~${debstr}).***"
  dch -b --distribution="${DISTRIBUTION}" \
    --newversion="${AUTO_VERSION}~${debstr}" \
    -- "Automated package build."
fi

ATOMIC_JOB_NAME=$( echo $JOB_NAME |cut -d / -f 1 )
PACKAGE=${ATOMIC_JOB_NAME%-source*}
UPSTREAM_VERSION="$( echo $ORIG_VERSION |cut -d \- -f 1 )"

for tar_component in $MULTITAR_SOURCE; do
  orig_name=`pristine-tar list |grep ${PACKAGE}_${UPSTREAM_VERSION}.orig-${tar_component}.tar`
  pristine-tar checkout ../${orig_name}
done

git-buildpackage --git-ignore-new --git-ignore-branch -uc -us -nc -d -S -i -I --source-option=--unapply-patches
