#!/bin/bash -x
# Purpose: generate Debian source package based on project's git repository
# schema:
# $debian_dir: and one directory for every distribution
# $debian_auto_version: how the automatic version is created
# $tagbase: tag to use for git describe
cd source

# debug info
env

# defaults
build_tag=false
TAG=unknown
BASE_DIR=${debian_dir:-"pkg"}
#BASE_DIR=${debian_dir:-"."}

if [ -n "$GIT_BRANCH" ] ; then
  case "$GIT_BRANCH" in
    origin/tags/*)
      build_tag=true
      TAG=${GIT_BRANCH#origin/tags/}
      ;;
  esac
fi

if [ ! -d "$BASE_DIR" -a ! -d debian ]; then
  echo 'No $BASE_DIR nor debian/ found on source'
  exit 1
fi

git clean -fxd

if [ "$BASE_DIR"X != debianX ]; then
  mkdir -p debian
  cp -aL "${BASE_DIR}"/"${distribution}"/* debian/
  rm -rf "$BASE_DIR"
fi


export DEBEMAIL="CFEngine Debian Team <debain-team@cfengine.com>"

ORIG_VERSION=$(dpkg-parsechangelog --count 1 | awk '/^Version/ {print $2}')
TIMESTAMP="$(date -u +%Y%m%d%H%M%S)"
DISTRIBUTION=$(dpkg-parsechangelog --count 1 | awk '/^Distribution/ {print $2}')
AUTO_VERSION="${ORIG_VERSION}+0~${TIMESTAMP}.${BUILD_NUMBER}"

if [ -n "$debian_auto_version" ]; then
  case "$debian_auto_version" in
    sems)
      DESCRIBE=$(git describe --match "${tagbase}" --always)
      echo "*** setting sems auto_version from ${DESCRIBE} ***"
      DESCRIBE=$(echo -n ${DESCRIBE}| sed 's/^.*-\([0-9]\+\)-\([a-zA-Z0-9]\+\)$/\1~\2/')
      AUTO_VERSION="${ORIG_VERSION}+0~${DESCRIBE}"
      ;;
    esac
fi

if "$build_tag" ; then
  echo "*** Building a tagged version (${TAG}).***"
  dch -b --distribution="${DISTRIBUTION}" \
    --newversion="${ORIG_VERSION}+${distribution}" \
    -- "Automated package build for tag $TAG and distribution $distribution."
else
  echo "*** Building version (${AUTO_VERSION}+${distribution}).***"
  dch -b --distribution="${DISTRIBUTION}" \
    --newversion="${AUTO_VERSION}+${distribution}" \
    -- "Automated package build."
fi

git-buildpackage --git-ignore-new --git-ignore-branch -uc -us -nc -d -S -i -I --source-option=--unapply-patches
