#!/bin/bash
# Purpose: prepare setup and invoke Debian binary package build

# configuration for build-and-provide-package and its tools
#export DEB_BUILD_OPTIONS="parallel=$(nproc)"
export BUILD_ONLY=true
export SUDO_CMD=sudo
export POST_BUILD_HOOK=/home/admin/cfengine-deb-jenkins/scripts/jdg-debc
export MAIN_ARCHITECTURE=amd64
export METADIST=$distribution

# set specific mirror when building for Ubuntu
case "$distribution" in
  raspwheezy)
    export DIST=wheezy
    export distribution=wheezy
    export COWBUILDER_BASE="/var/cache/pbuilder/base-${METADIST}-${architecture}.cow"
    ;;
  raspjessie)
    export DIST=jessie
    export distribution=jessie
    export COWBUILDER_BASE="/var/cache/pbuilder/base-${METADIST}-${architecture}.cow"
    ;;
esac

export COWBUILDER_DIST=$distribution

# execute main jenkins-debian-glue script
/usr/bin/build-and-provide-package
